// ══════════════════════════════════════════════════════════════
// NUDGE — Gmail API Utilities
// Privacy-by-design:
//   - Dates only for last-contact detection
//   - Snippets (auto-truncated by Google, ~150 chars) for context
//   - Never store or transmit full email body or subject
// ══════════════════════════════════════════════════════════════

export interface GmailTokens {
  access_token:  string;
  refresh_token: string;
  expiry_date?:  number;
}

export interface ContactDate {
  leadId:        string;
  leadEmail:     string;
  lastEmailDate: string | null; // "YYYY-MM-DD"
  direction:     "sent" | "received" | "both" | null;
}

export interface ConversationContext {
  snippets:    ConversationSnippet[];
  threadCount: number;
}

export interface ConversationSnippet {
  date:      string;        // "YYYY-MM-DD"
  direction: "sent" | "received";
  snippet:   string;        // Google's own truncated preview (~150 chars)
}

// ─── Build Google OAuth URL ───────────────────────────────────
export function buildGmailAuthUrl(userId: string): string {
  const params = new URLSearchParams({
    client_id:     process.env.GOOGLE_CLIENT_ID!,
    redirect_uri:  `${(process.env.NEXT_PUBLIC_APP_URL ?? "").replace(/\/$/, "")}/api/gmail/callback`,
    response_type: "code",
    scope:         "https://www.googleapis.com/auth/gmail.readonly",
    access_type:   "offline",
    prompt:        "consent",
    state:         userId,
  });
  return `https://accounts.google.com/o/oauth2/v2/auth?${params}`;
}

// ─── Exchange code for tokens ─────────────────────────────────
export async function exchangeCodeForTokens(code: string): Promise<GmailTokens> {
  const res = await fetch("https://oauth2.googleapis.com/token", {
    method:  "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      code,
      client_id:     process.env.GOOGLE_CLIENT_ID!,
      client_secret: process.env.GOOGLE_CLIENT_SECRET!,
      redirect_uri:  `${(process.env.NEXT_PUBLIC_APP_URL ?? "").replace(/\/$/, "")}/api/gmail/callback`,
      grant_type:    "authorization_code",
    }),
  });
  if (!res.ok) throw new Error(`Token exchange failed: ${await res.text()}`);
  const data = await res.json();
  return {
    access_token:  data.access_token,
    refresh_token: data.refresh_token,
    expiry_date:   Date.now() + data.expires_in * 1000,
  };
}

// ─── Refresh expired token ────────────────────────────────────
export async function refreshAccessToken(refreshToken: string): Promise<string> {
  const res = await fetch("https://oauth2.googleapis.com/token", {
    method:  "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      refresh_token: refreshToken,
      client_id:     process.env.GOOGLE_CLIENT_ID!,
      client_secret: process.env.GOOGLE_CLIENT_SECRET!,
      grant_type:    "refresh_token",
    }),
  });
  if (!res.ok) throw new Error("Failed to refresh Gmail access token");
  return (await res.json()).access_token;
}

// ─── Get last email date (for last-contact detection) ─────────
export async function getLastEmailDateForContact(
  accessToken: string,
  contactEmail: string
): Promise<{ date: string | null; direction: "sent" | "received" | "both" | null }> {
  const url = new URL("https://gmail.googleapis.com/gmail/v1/users/me/messages");
  url.searchParams.set("q", `from:${contactEmail} OR to:${contactEmail}`);
  url.searchParams.set("maxResults", "5");

  const listRes = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!listRes.ok) {
    if (listRes.status === 401) throw new Error("GMAIL_UNAUTHORIZED");
    return { date: null, direction: null };
  }

  const listData = await listRes.json();
  if (!listData.messages?.length) return { date: null, direction: null };

  const msgId  = listData.messages[0].id;
  const msgRes = await fetch(
    `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msgId}?format=metadata&metadataHeaders=From&metadataHeaders=To`,
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  if (!msgRes.ok) return { date: null, direction: null };
  const msgData = await msgRes.json();

  const epochMs = parseInt(msgData.internalDate ?? "0", 10);
  if (!epochMs) return { date: null, direction: null };

  const date      = new Date(epochMs).toISOString().slice(0, 10);
  const headers   = msgData.payload?.headers ?? [];
  const from      = headers.find((h: { name: string; value: string }) => h.name === "From")?.value ?? "";
  const direction = from.toLowerCase().includes(contactEmail.toLowerCase()) ? "received" : "sent";

  return { date, direction };
}

// ─── NEW: Get conversation snippets for contextual nudges ─────
// Reads the last 5 email SNIPPETS between user and a contact.
// The snippet is generated by Google itself (~150 chars max).
// We never read, store or transmit the full email body.
export async function getConversationContext(
  accessToken:  string,
  contactEmail: string,
  maxMessages = 5
): Promise<ConversationContext> {
  const url = new URL("https://gmail.googleapis.com/gmail/v1/users/me/messages");
  url.searchParams.set("q", `from:${contactEmail} OR to:${contactEmail}`);
  url.searchParams.set("maxResults", String(maxMessages));

  const listRes = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!listRes.ok) {
    if (listRes.status === 401) throw new Error("GMAIL_UNAUTHORIZED");
    return { snippets: [], threadCount: 0 };
  }

  const listData = await listRes.json();
  if (!listData.messages?.length) return { snippets: [], threadCount: 0 };

  const snippets: ConversationSnippet[] = [];

  for (const msg of listData.messages.slice(0, maxMessages)) {
    // format=minimal gives us id, threadId, labelIds, snippet — nothing more
    const msgRes = await fetch(
      `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=minimal`,
      { headers: { Authorization: `Bearer ${accessToken}` } }
    );

    if (!msgRes.ok) continue;
    const msgData = await msgRes.json();

    const epochMs = parseInt(msgData.internalDate ?? "0", 10);
    if (!epochMs || !msgData.snippet) continue;

    const date = new Date(epochMs).toISOString().slice(0, 10);

    // Determine direction from label: SENT means the user sent it
    const isSent    = (msgData.labelIds ?? []).includes("SENT");
    const direction = isSent ? "sent" : "received";

    snippets.push({
      date,
      direction,
      snippet: msgData.snippet, // Already truncated by Google to ~150 chars
    });

    await new Promise((r) => setTimeout(r, 80)); // Respect rate limits
  }

  // Count unique threads to gauge conversation depth
  const uniqueThreads = new Set(listData.messages.map((m: { threadId: string }) => m.threadId)).size;

  return { snippets, threadCount: uniqueThreads };
}

// ─── Check if user sent an email to a contact after a given timestamp ────────
// Used by the follow-up detection cron to auto-track behavior.
export async function checkIfEmailSentAfter(
  accessToken:  string,
  contactEmail: string,
  afterDate:    Date
): Promise<boolean> {
  const afterEpochSec = Math.floor(afterDate.getTime() / 1000);

  // Gmail query: sent TO this contact, after the nudge timestamp
  const url = new URL("https://gmail.googleapis.com/gmail/v1/users/me/messages");
  url.searchParams.set("q", `to:${contactEmail} after:${afterEpochSec} in:sent`);
  url.searchParams.set("maxResults", "1");

  const res = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!res.ok) {
    if (res.status === 401) throw new Error("GMAIL_UNAUTHORIZED");
    return false;
  }

  const data = await res.json();
  return (data.messages?.length ?? 0) > 0;
}

// ─── Scan all leads (date only) ───────────────────────────────
export async function scanLeadsForUser(
  accessToken: string,
  leads: { id: string; email: string | null }[]
): Promise<ContactDate[]> {
  const results: ContactDate[] = [];
  const leadsWithEmail = leads.filter((l) => l.email?.includes("@"));

  for (const lead of leadsWithEmail) {
    try {
      const { date, direction } = await getLastEmailDateForContact(accessToken, lead.email!);
      results.push({ leadId: lead.id, leadEmail: lead.email!, lastEmailDate: date, direction });
      await new Promise((r) => setTimeout(r, 100));
    } catch (err) {
      if (err instanceof Error && err.message === "GMAIL_UNAUTHORIZED") throw err;
      console.error(`Gmail scan failed for lead ${lead.id}:`, err);
    }
  }

  return results;
}
